### PR TITLE
Support for functions

### PR DESCRIPTION
**Pull request by phayes**
This PR implements preliminary support for functions. 

Not ready for merge yet, but the skeleton is here and ready for feedback. 

Everything is fairy straightforward with the exception of JSONSchema.   Instead of adding a dependency on the `schemars` crate and requiring a fully-typed [SchemaObject](https://docs.rs/schemars/latest/schemars/schema/struct.SchemaObject.html), which is hellish, I simply used `serde_json::Value` and left it up to the user to either use `schemars`, or construct something by hand, or deserialize something etc. 

I'll add some good documentation to this before this PR is ready to merge.

### CODE REVIEW

**Comment by Kodylow** [comment]
Is this ready for testing/review @phayes ? Got a couple function-y things I'm trying to do haha

**Comment by phayes** [comment]
Hi @Kodylow ,

Yes!  Although I snuck a bunch of other changes in here as well.  Let me know if you'd like me to split it into a bunch of different PRs. 

The only thing missing is documentation.

**Comment by phayes** [comment]
I've marked this ready for review:

1. Function calling works with both standard API and streaming API
2. To aid in debugging function calls (which is often needed), I've added an optional dependency on the "log" crate and added some debugging log points. 
3. I've documented calling functions in `lib.rs`, but haven't added documentation for calling functions in the stream API (it's quite complicated and will require a follow up PR)
4. I've added better handing of stream errors (needed to have visibility into errors in calling function when streaming)

**Comment by phayes** [comment]
My apologies, as I did some final testing I ran into a bunch of small issues that are now fixed.   I've also added `calling_fuction` and `calling_function_stream` to the `examples` directory.  I've also impl'ed `Default` for `ChatMessage`

I don't intend on making any more changes now. Please review!

**Review by tjardoo — APPROVED** [review]

**Comment by Kodylow** [comment]
🥳

**Pull request merged**
