### PR TITLE
Enforce models

### PR DESCRIPTION
**Pull request by Kodylow**
enforces openai models instead of using strings

### CODE REVIEW

**Comment by tjardoo** [comment]
I like the idea to separate the models (`Chat`, `Embeddings`, `TTS`, 'DallE` etc.). But if we want to enforce the models on the resources (ie. `ChatCompletionParameters`) it will be more difficult to add a custom model + we'll have to list all possible models (in case anyone wants to use a legacy model or a newer version if it's not yet added to the list). What do you think of keeping the separation of models but to keep `pub model: String` on the resources?

**Comment by Kodylow** [comment]
That makes sense to me, especially with fine-tune models for gpt-3 pricing coming down ppl might really use it haha, will update

**Comment by tjardoo** [comment]
I have added this to #26. Kept the model names configurable as String (Enum model names is optional).

**Comment by Kodylow** [comment]
good to go!

**Pull request closed without merging**
