### PR TITLE
Convert ChatMessage to enum

### PR DESCRIPTION
**Pull request by tjardoo**

### CODE REVIEW

**Review by philpax — APPROVED** [review]
Looks great! Apologies for misnaming the Clippy step, should've taken a closer look at the copy-paste 😂 

You may also want to update `DeltaChatMessage`; I think you'd be able to delete the `Role` enum then?

**Comment by tjardoo** [comment]
I converted the `DeltaChatMessage` to an enum. The first delta response contains the role. All subsequent responses don't contain the role anymore - therefore I had to add the enum variant 'Untagged'. Any suggestions/alternatives to make it better? Thanks

**Comment by tjardoo** [comment]
```rust
let stream = client.chat().create_stream(parameters).await.unwrap();

let mut tracked_stream = RoleTrackingStream::new(stream);

while let Some(response) = tracked_stream.next().await {
```

@philpax I've added a role tracking stream that that adds the 'role' so the `Untagged` variant is not needed on the client-side. I'm still doubting whether to make it the default - such that the `create_stream()` returns the role tracking stream by default. What do you think of this setup?

**Comment by philpax** [comment]
Seems pretty reasonable to me! I'd go with this for now and see how people feel about it. We're not currently using streaming, so I don't have a strong preference, but this looks like a good solution. 

The only thing I'd suggest is adding documentation to clarify what it's for on both `RoleTrackingStream` and `DeltaChatMessage::Untagged`, so that users can figure out that it's available from looking at the docs / looking at how to handle `Untagged` in their editor.

**Pull request merged**
