### PR TITLE
Add text and image content part implementation for chat message content

### PR DESCRIPTION
**Pull request by Marlinski**
fix issue #98

### CODE REVIEW

**Comment by tjardoo** [comment]
Resolves #98

**Comment by Marlinski** [comment]
Is there anything blocking the merge?

**Comment by Marlinski** [comment]
Okay! Happy to review if you make any changes.

Tjardo ***@***.***> 于 2024年10月22日周二 17:44写道：

**Comment by tjardoo** [comment]
I've added also support for the new chat audio. Resolves #100 
@Marlinski any comments/improvements before merging?

**Comment by Marlinski** [comment]
I forgot to update the examples thanks for doing it. It lgtm :)

**Pull request merged**
